# Generated by Django 3.2 on 2021-05-04 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StructureCategory',
        ),
    ]
