# Generated by Django 3.2 on 2021-05-04 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_structurecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='str_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysite.structurecategory', verbose_name='Категория'),
        ),
    ]
